[phases.setup]
nixPkgs = [
  "php84",
  "php83Extensions.bcmath",
  "php83Extensions.gd",
  "php83Extensions.curl",
  "php83Extensions.zip",
  "php83Extensions.exif",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.openssl"
]